version: '3'

services:
    poc_sf_bigquery_nginx:
        container_name: poc_sf_bigquery_nginx
        image: nginx:stable
        networks:
            - poc_sf_bigquery
        ports:
            - "8008:80"
        volumes:
            - .:/var/www/html:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
        working_dir: /etc/nginx/conf.d

    poc_sf_bigquery_phpfpm:
        container_name: poc_sf_bigquery_phpfpm
        build:
            context: ./docker/phpfpm
        expose:
            - 9000
        networks:
            - poc_sf_bigquery
        volumes:
            - .:/var/www/html:cached
        working_dir: /var/www/html

volumes:
    poc_sf_bigquery_redis_volume:
        driver: local

networks:
    poc_sf_bigquery:
        external: true
